# Generated by Django 4.0 on 2025-10-24 07:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description_short', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Полное описание (HTML)')),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/%Y/%m/%d/', verbose_name='Картинка')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='locations.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Изображение места',
                'verbose_name_plural': 'Изображения места',
                'ordering': ['position', 'id'],
            },
        ),
    ]
