# Generated by Django 5.2.7 on 2025-10-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position'], 'verbose_name': 'Изображение локации', 'verbose_name_plural': 'Изображения локации'},
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(upload_to='places/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Позиция'),
        ),
    ]
