# Generated by Django 5.2.7 on 2025-10-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_place_options_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(verbose_name='Полное описание (HTML)'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
